/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Dimension;
import javax.swing.*;

/**
 *
 * @author trang
 */
public class Restaurant_Home extends javax.swing.JFrame {

    /**
     * Creates new form Restaurant_home
     */
    public Restaurant_Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Logout_button = new javax.swing.JButton();
        AddM_button = new javax.swing.JButton();
        ViewM_button = new javax.swing.JButton();
        viewOrders_button = new javax.swing.JButton();
        Online_button = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restaurant");
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(104, 4, 112));

        Logout_button.setBackground(new java.awt.Color(255, 102, 102));
        Logout_button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Logout_button.setForeground(new java.awt.Color(255, 255, 255));
        Logout_button.setText("Log out");
        Logout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout_buttonActionPerformed(evt);
            }
        });

        AddM_button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AddM_button.setText("Add Menu");
        AddM_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddM_buttonActionPerformed(evt);
            }
        });

        ViewM_button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ViewM_button.setText("View Menu");
        ViewM_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewM_buttonActionPerformed(evt);
            }
        });

        viewOrders_button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        viewOrders_button.setText("Orders");
        viewOrders_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrders_buttonActionPerformed(evt);
            }
        });

        Online_button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Online_button.setText("Online/Offline");
        Online_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Online_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(AddM_button)
                .addGap(18, 18, 18)
                .addComponent(ViewM_button)
                .addGap(120, 120, 120)
                .addComponent(viewOrders_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(Online_button)
                .addGap(74, 74, 74)
                .addComponent(Logout_button)
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Logout_button)
                    .addComponent(AddM_button)
                    .addComponent(ViewM_button)
                    .addComponent(viewOrders_button)
                    .addComponent(Online_button))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/home_background.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 890, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewM_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewM_buttonActionPerformed
        // TODO add your handling code here:
        Restaurant_ViewMenu viewFrame = new Restaurant_ViewMenu();
        viewFrame.setVisible(true);
        viewFrame.setLocation(this.getX()+100, this.getY()+120);
    }//GEN-LAST:event_ViewM_buttonActionPerformed

    private void AddM_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddM_buttonActionPerformed
        // TODO add your handling code here:
        Restaurant_AddMenuItem addFrame = new Restaurant_AddMenuItem();
        addFrame.setVisible(true);
        addFrame.setLocationRelativeTo(this);
    }//GEN-LAST:event_AddM_buttonActionPerformed

    private void Logout_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout_buttonActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "You want to log out?", "Select", JOptionPane.YES_NO_OPTION);
        if(a == 0) {
            LoginPage loginFrame = new LoginPage();
            loginFrame.setMinimumSize(new Dimension(800, 535));
            loginFrame.setVisible(true);
            loginFrame.pack();
            loginFrame.setLocationRelativeTo(this);
            this.dispose();
        }
    }//GEN-LAST:event_Logout_buttonActionPerformed

    private void viewOrders_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrders_buttonActionPerformed
        // TODO add your handling code here:
        Restaurant_ViewOrders ordersFrame = new Restaurant_ViewOrders();
        ordersFrame.setVisible(true);
        ordersFrame.setLocation(this.getX()+100, this.getY()+120);
    }//GEN-LAST:event_viewOrders_buttonActionPerformed

    private void Online_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Online_buttonActionPerformed
        // TODO add your handling code here:
        if(Online_button.isSelected()) {
            // Set restaurant's availability "true"
        }
        else {
            // Set restaurant's availability "false"
        }
    }//GEN-LAST:event_Online_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Restaurant_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Restaurant_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Restaurant_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Restaurant_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Restaurant_home().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddM_button;
    private javax.swing.JButton Logout_button;
    private javax.swing.JToggleButton Online_button;
    private javax.swing.JButton ViewM_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton viewOrders_button;
    // End of variables declaration//GEN-END:variables
}
